blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_post_view, name='create_blog_post_view'),
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),
    path('post/<slug:post_slug>/edit/', post_edit_view, name='post_edit_view'),
    path('post/<slug:post_slug>/delete/', delete_post, name='delete_post_view'),
    path('fav-update/', fav_update, name='fav_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from page.views import *
from blog.views import search_view

urlpatterns = [
    
    path('', home_view, name='home_view'),
    path('blog/', forum_page_view, name='forum_page_view'),

    # Search:
    path('search/', search_view, name='search_view'),

    # User
    path('user/', include('user.urls', namespace='user')),
    # Read
    path('read/', include('read.urls', namespace='read')),

    # Blog
    path('blog/', include('blog.urls', namespace='blog')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login_view'),
    path('profile/edit/', profile_edit_view, name='profile_edit_view'),
    path('register/', register_view, name='register_view'),
    path('logout/', logout_view, name='logout_view'),
    path('favs/', show_user_fav_view, name='show_user_fav_view'),
]

templates/core/_footer.html
<div class="bg-light">
    <footer class="py-3">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
      </ul>
      <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
    </footer>
</div>

templates/core/_header.html
{% load static %}
<header id="head">
    <div class="w-50 d-flex flex-column align-items-center justify-content-center h-100">
        <h1>Embrace Your Inner Strength</h1>
        <h6>Unlock Your Potential, Ignite Your Passion. Start Now!</h6>
        <a href="{% url "forum_page_view" %}" class="btn btn-dark border rounded-5 mt-2">Get Started</a>
    </div>
</header>
<hr>

templates/core/_hero.html
{% load static %}
<main>
    <section id="hero">
        <article id="hero-article"></article>
        <div class="d-flex flex-column align-items-center justify-content-center h-100 my-5">
            <h2>Overcome the Mind's Limits</h2>
            <h6>Your Gateway to Infinite Possibilities. Join the community and start your journey today.</h6>
            <a href="{% url "user:register_view" %}" class="btn btn-dark border rounded-5 mt-2 px-3 py-2">Join Us</a>
        </div>
    </section>

    <section id="hero-2" class="d-flex justify-content-between">
        <article class="overflow-hidden" id="hero-article-2"><img src="{% static "img/hero-content-2.jpeg" %}" alt=""></article>
        <div class="d-flex flex-column align-items-center justify-content-center p-3">
            <h2>Transform Your Intriguing Idea into Reality</h2>
            <h5>Discover a world of limitless possibilities. </h5>
            <h6>Your idea, your journey, your community – all at your fingertips. Start now, and make it happen.</h6>
            <a href="{% url "forum_page_view" %}" class="btn btn-dark border rounded-5 mt-2 px-3 py-2">Start Reading</a>
        </div>
        <article class="overflow-hidden" id="hero-article-3"><img src="{% static "img/hero-content-3.png" %}" alt=""></article>
    </section>
</main>

templates/core/_messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}

templates/core/_navbar.html
{% load thumbnail %}
{% load static %}

<nav class="navbar navbar-expand-lg bg-light navbar-light p-3 sticky-top">
    <div class="container-fluid">
        <a href="{% url "home_view" %}" class="text-decoration-none text-dark fs-5">ShareHub ⎋</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2"
          aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label" aria-modal="true">
        <div class="offcanvas-header mb-0 border border-bottom">
          <a href="{% url "home_view" %}" class="text-decoration-none text-dark fs-5">ShareHub ⎋</a>
          <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 gap-1 pe-3">

            <form action="{% url "search_view" %}" method='GET' class="d-flex mt-2 mb-1 mx-4 ms-auto w-100 position-relative" role="search">
              <i class="fa-solid fa-magnifying-glass text-dark"></i>
              <input name='q' class="form-control me-2 border rounded-5 px-4" type="search" placeholder="Search" aria-label="Search">
            </form>
            {% if not request.user.is_authenticated %}                
              <li class="nav-item">
                  <a class="btn btn-secondary border w-100 rounded-5" aria-current="page" href="{% url "user:login_view" %}">Log In</a>
              </li>
              <li class="nav-item">
                  <a class="btn btn-dark border w-100 rounded-5" aria-current="page" href="{% url "user:register_view" %}">Register</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="btn btn-outline-dark border w-100 rounded-5" aria-current="page" href="{% url "forum_page_view" %}">Forum</a>
            </li>
            {% if request.user.is_authenticated %}
              <ul class="dropdown text-start mb-0 mt-2 p-0">
                <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false">
                  {% if request.user.profile.avatar|thumbnail_url:'avatar' %}
                    <img src="{{ request.user.profile.avatar|thumbnail_url:'avatar' }}" alt="" width="32" height="32" class="rounded-circle m-1">
                  {% else %}
                    <img src="{% static "./img/default_user.jpeg" %}" class="rounded-circle" alt="" width="32" height="32">
                  {% endif %}
                    <span class="text-dark">{{ request.user.first_name }}</span>
                </a>
                <ul class="dropdown-menu text-small dropdown-menu-lg-end dropdown-menu-start">
                    <li><a class="dropdown-item" href="{% url "blog:create_blog_post_view" %}">Write</a></li>                     
                    <li><a class="dropdown-item" href="{{request.user.profile.get_absolute_url}}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url "user:profile_edit_view" %}">Edit Profile</a></li>
                    <li><a class="dropdown-item" href="{{ request.user.profile.get_fav_url }}">Favs</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li class="nav-item">
                      <a class="dropdown-item" href="{% url "user:logout_view" %}">Logout</a>
                    </li> 
                </ul>
              </ul>
            {% endif %}
            
          </ul>
        </div>
      </div>

      <div class="collapse navbar-collapse">

        <form action="{% url "search_view" %}" method='GET' class="d-flex mx-4 ms-auto w-50 position-relative" role="search">
          <i class="fa-solid fa-magnifying-glass text-dark"></i>
          <input name='q' class="form-control me-2 border rounded-5 px-4" type="search" placeholder="Search" aria-label="Search">
        </form>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap-1">
          <li class="nav-item">
              <a class="btn btn-outline-dark border rounded-5" aria-current="page" href="{% url "forum_page_view" %}">Forum</a>
          </li>
          {% if not request.user.is_authenticated %}                
            <li class="nav-item">
                <a class="btn btn-secondary border rounded-5" aria-current="page" href="{% url "user:login_view" %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-dark border rounded-5" aria-current="page" href="{% url "user:register_view" %}">Register</a>
            </li>
          {% else %}
            
            <ul class="dropdown text-start mb-0 p-0">
              <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false">
                {% if request.user.profile.avatar|thumbnail_url:'avatar' %}
                  <img src="{{ request.user.profile.avatar|thumbnail_url:'avatar' }}" alt="" width="32" height="32" class="rounded-circle m-1">
                {% else %}
                  <img src="{% static "./img/default_user.jpeg" %}" class="rounded-circle" alt="" width="32" height="32">
                {% endif %}
                  <span class="text-dark">{{ request.user.first_name }}</span>
              </a>
              <ul class="dropdown-menu text-small dropdown-menu-lg-end dropdown-menu-start">
                  <li><a class="dropdown-item" href="{% url "blog:create_blog_post_view" %}">Write</a></li>                     
                  <li><a class="dropdown-item" href="{{request.user.profile.get_absolute_url}}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url "user:profile_edit_view" %}">Edit Profile</a></li>
                  <li><a class="dropdown-item" href="{{ request.user.profile.get_fav_url }}">Favs</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="nav-item">
                    <a class="dropdown-item" href="{% url "user:logout_view" %}">Logout</a>
                  </li> 
              </ul>
            </ul>
          {% endif %}
        </ul>

      </div>
        
      
    </div>
  </nav>

    

templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ShareHub</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>

    {% include "core/_messages.html" %}
    <!-- Navbar -->
   {% include "core/_navbar.html" %}
    <!-- Navbar End -->

    {% block content %}
    
    {% endblock content %}
    

    {% include "core/_footer.html" %}
    <script src="https://kit.fontawesome.com/f478418874.js" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    {% block script %}
    
    {% endblock script %}
  </body>
</html>