blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_post_view, name='create_blog_post_view'),
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),
    path('post/<slug:post_slug>/edit/', post_edit_view, name='post_edit_view'),
    path('post/<slug:post_slug>/delete/', delete_post, name='delete_post_view'),
    path('fav-update/', fav_update, name='fav_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from page.views import *
from blog.views import search_view

urlpatterns = [
    
    path('', home_view, name='home_view'),
    path('blog/', forum_page_view, name='forum_page_view'),

    # Search:
    path('search/', search_view, name='search_view'),

    # User
    path('user/', include('user.urls', namespace='user')),
    # Read
    path('read/', include('read.urls', namespace='read')),

    # Blog
    path('blog/', include('blog.urls', namespace='blog')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Third Party Apps:
from autoslug import AutoSlugField
from tinymce import models as tinymce_models

# Create your models here.

class CommonModel(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from = 'title', unique=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ('title', )

class Category(CommonModel):

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:category_view", 
            kwargs={
                "category_slug": self.slug
            }
        )
    

class Tag(CommonModel):

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:tag_view',
            kwargs={
                'tag_slug': self.slug
            }
        )

class BlogPost(CommonModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag)
    cover_image = models.ImageField(upload_to="post")
    content = tinymce_models.HTMLField(blank=True, null=True)
    view_count = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-created_at', )

    def get_absolute_url(self):
        return reverse(
            'read:post_detail_view',
            kwargs={
                'user_slug': self.user.profile.slug,
                'post_slug': self.slug,
            }
        )
    
    def get_post_edit_url(self):
        return reverse(
            'blog:post_edit_view',
            kwargs={
                'post_slug': self.slug,
            }
        )
    
    def get_post_delete_url(self):
        return reverse(
            'blog:delete_post_view',
            kwargs={
                'post_slug': self.slug,
            }
        )

    
class UserPostFav(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.user.first_name)

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import *
from django.core import validators
from django.forms import widgets


class BlogPostModelForm(forms.ModelForm):
    tag = forms.CharField()
    content = forms.CharField(widget=TinyMCE(attrs={'cols':40, 'rows': 20}))
    title = forms.CharField(validators=[validators.MinLengthValidator(3, message="Oppss.. en az 3 karakter olmali")])

    class Meta:
        model = BlogPost
        fields = [
            'title',
            'cover_image',
            'content',
            'category',
            'tag',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['content'].widget = widgets.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment...'})

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
from .forms import *
from .models import *
import json


# Create your views here.

login_required(login_url='user:login_view')
def fav_update(request):
    if request.method == 'POST':
        post = get_object_or_404(BlogPost, slug = request.POST.get('slug'))
        if post:
            post_fav, created = UserPostFav.objects.get_or_create(
                user = request.user,
                post = post,
            )
            if not created:
                post_fav.is_deleted =  not post_fav.is_deleted
                post_fav.save()

    
    return JsonResponse({'status': 200})



login_required(login_url='user:login_view')
def create_blog_post_view(request):
    title = 'Yeni Blog Post: '
    form = BlogPostModelForm()
   
    if request.method == 'POST':
        form = BlogPostModelForm(request.POST or None, request.FILES or None)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            tags_json = form.cleaned_data.get('tag')
            tags = json.loads(tags_json)
            for item in tags:
                value = item["value"]
                tag_item, created = Tag.objects.get_or_create(title=value.lower())
                tag_item.is_active = True
                tag_item.save()
                post.tag.add(tag_item)
            messages.success(request, 'Your blog post has been successfully saved.')
            return redirect('home_view')

    context = dict(
        form = form,
        title = title,
    )
    return render(request, 'comon_components/form.html', context)


def tag_view(request, tag_slug):
    tag = get_object_or_404(Tag, slug = tag_slug)
    posts = BlogPost.objects.filter(tag = tag)
    if request.user.is_authenticated:
        ids = request.user.userpostfav_set.filter(is_deleted=False).values_list('post_id', flat=True)
        favs=BlogPost.objects.filter(id__in=ids, is_active=True)

        context = dict(
        tag = tag,
        favs = favs
        )
        return render(request, 'blog/post_list.html', context)

        
    context = dict(
        tag = tag,
    )

    return render(request, 'blog/post_list.html', context)


def category_view(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    posts = BlogPost.objects.filter(category = category)
    if request.user.is_authenticated:
        ids = request.user.userpostfav_set.filter(is_deleted=False).values_list('post_id', flat=True)
        favs=BlogPost.objects.filter(id__in=ids, is_active=True)

        context = dict(
        category = category,
        favs = favs
        )
        return render(request, 'blog/post_list.html', context)

    context = dict(
        category = category,
    )

    return render(request, 'blog/post_list.html', context)

def search_view(request):
    if 'q' in request.GET and request.GET.get('q'):

        if request.user.is_authenticated:
            ids = request.user.userpostfav_set.filter(is_deleted=False).values_list('post_id', flat=True)
            favs=BlogPost.objects.filter(id__in=ids, is_active=True)

            q = request.GET.get('q')
        
            categories = Category.objects.filter(title__contains = q)    
            tags = Tag.objects.filter(title__contains = q)    
            posts = BlogPost.objects.filter(title__contains = q) or BlogPost.objects.filter(category__in = categories) or BlogPost.objects.filter(tag__in = tags)
            
            return render(request, 'blog/search.html', {
                        'q':q,
                        'posts':posts,
                        'favs':favs
            })
        

        q = request.GET.get('q')
        
        categories = Category.objects.filter(title__contains = q)    
        tags = Tag.objects.filter(title__contains = q)    
        posts = BlogPost.objects.filter(title__contains = q) or BlogPost.objects.filter(category__in = categories) or BlogPost.objects.filter(tag__in = tags)
        
        return render(request, 'blog/search.html', {
            'q':q,
            'posts':posts,
        })
        


    return render(request, 'blog/search.html', {})


login_required(login_url='user:login_view')
def post_edit_view(request, post_slug):
    
    post = get_object_or_404(BlogPost, slug = post_slug)

    if not post.user == request.user:
        messages.warning(request, 'You cannot edit this post information.')
        return redirect('home_view')
    

    title = post.title
    form = BlogPostModelForm(instance=post)

    if request.method == 'POST':
        form = BlogPostModelForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            tags = json.loads(form.cleaned_data.get('tag'))
            for item in tags:
                tag_item, created = Tag.objects.get_or_create(title=item.get('value').lower())
                tag_item.is_active = True
                tag_item.save()
                f.tag.add(tag_item)
            messages.success(request, 'Your blog post has been successfully edited.')
            return redirect('home_view')

    context = dict(
        title = title,
        form = form
    )

    return render(request, 'comon_components/form.html', context)



def delete_post(request, post_slug):
    post = get_object_or_404(BlogPost, slug = post_slug)

    if not post.user == request.user:
        messages.warning(request, 'You cannot delete this post information.')
        return redirect('home_view')

    if request.method == 'POST':
        post.delete()
        return redirect('home_view')
    else:
        return render(request, 'blog/delete.html', {
            'post': post
        })
    

blog/templates/blog/delete.html
{% extends 'core/base.html' %}

{% block content %}

    <form method="POST" class="p-3 text-center">
        {% csrf_token %}
            <h4>{{post.title}}</h4>
            <p>You sure you want to delete this post?</p>

            
        <input class="btn btn-primary" type="submit" value="Delete">
        <a class="btn btn-secondary" href="{{ post.get_absolute_url }}">Nevermind</a>
    </form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "core/base.html" %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2 mt-5 bg-light border p-5">
            {% if category %}
                <h1>{{ category.title }}</h1>
            {% elif tag %}
                <h1>{{ tag.title }}</h1>
            {% elif favs %}
                <h1>{{ title }}</h1>
            {% endif %}
        </div>
        <div class="col-lg-8 offset-lg-2 mt-5">
            {% if category %}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "home_view" %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url "forum_page_view" %}">Forum</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ category.title }}</li>
                    </ol>
                </nav>
                {% with posts=category.blogpost_set.all %}
                    {% for post in posts %}
                        {% include "components/post.html" %}
                    {% endfor %}
                {% endwith %}
            {% elif tag %}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "home_view" %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url "forum_page_view" %}">Forum</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ tag.title }}</li>
                    </ol>
                </nav>
                {% with posts=tag.blogpost_set.all %}
                    {% for post in posts %}
                            {% include "components/post.html" %}
                    {% endfor %}
                {% endwith %}
            {% elif favs %}
                {% with posts=favs %}
                    {% for post in posts %}
                            {% include "components/post.html" %}
                    {% endfor %}
                {% endwith %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    {% include "comon_components/fav_update.html" %}

{% endblock script %}

blog/templates/blog/search.html
{% extends "core/base.html" %}


{% block content %} 
{% if q %}
    <h1 class="text-center mt-3">You searched for {{ q }}</h1>
    <h5 class="text-center">Here is what we found..</h5>
    <br>
    <div class="container">
    <div class="row justify-content-center">
        {% for post in posts %}
            <div class="col-lg-8">
                {% include "components/post.html" %}
            </div>
        {% endfor %}
    </div>
    </div>

{% else %}
    <h1 class="text-center">Hey! You Forgot To Search...</h1>

{% endif %}

{% endblock content %}


{% block script %}
    {% include "comon_components/fav_update.html" %}

{% endblock script %}